import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect } from 'react';
import heroBatailleNavaleC from "../public/assets/images/heroBatailleNavaleC.jpg";



import Image from 'next/image';
export default function Home() {

    return (
        <>
            <Head>
                <title>Accueil</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/engine.ico" />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
            </Head>
            <div className='bg-white py-4'>
        <div className='flex justify-between max-w-7xl mx-auto'>
        <Link href="/" className='text-2xl'>AE</Link>

          <ul className='flex items-center space-x-6'>
            <li><Link href="/">Accueil</Link></li>
            <li><Link href="/about">A propos</Link></li>
            <li><Link href="/realisations">Mes réalisation</Link></li>
          </ul>
        </div>
      </div>
            <h1 className='text-center'>Bataille Navale</h1>
            <div className='flex items-center justify-center'>
<Link className='text-white' href="https://github.com/Fabio83500/batailleNavaleEnC">https://github.com/Fabio83500/batailleNavaleEnC</Link>
            </div>
            <div className='max-w-7xl mx-auto text-white'>
                <Image src={heroBatailleNavaleC} width={400} height={600} />

            </div>

        </>
    )
}
