import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect } from 'react';
import Typewriter from 'typewriter-effect/dist/core';
import imgCV from "../public/assets/images/imgCv.jpg";

import gsb from "../public/assets/images/gsb_log.png";
import heroGsb from "../public/assets/images/heroGsb.jpg"

import Image from 'next/image';
export default function Home() {

    return (
        <>
            <Head>
                <title>Accueil</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/engine.ico" />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
            </Head>
            <div className='bg-white py-4'>
        <div className='flex justify-between max-w-7xl mx-auto'>
        <Link href="/" className='text-2xl'>FB</Link>

          <ul className='flex items-center space-x-6'>
            <li><Link href="/">Accueil</Link></li>
            <li><Link href="/about">A propos</Link></li>
            <li><Link href="/realisations">Mes réalisation</Link></li>
          </ul>
        </div>
      </div>
            <h1 className='text-center'>Galaxy Swiss Bourdin</h1>
            <div className='flex items-center justify-center'>
            <Image src={heroGsb} width={200} height={100} />
            
            </div>
            <div className='max-w-7xl mx-auto text-white'>
            <span className='my-4 block text-xl'>Le secteur d'activité</span>
            <p className='mb-8 text-sm'>L’industrie pharmaceutique est un secteur très lucratif dans lequel le mouvement de fusion acquisition
                est très fort. Les regroupements de laboratoires ces dernières années ont donné naissance à des entités gigantesques au sein desquelles le travail est longtemps resté organisé selon les anciennes structures.
                Des déboires divers récents autour de médicaments ou molécules ayant entraîné des complications
                médicales ont fait s'élever des voix contre une partie de l'activité des laboratoires : la visite médicale,
                réputée être le lieu d'arrangements entre l'industrie et les praticiens, et tout du moins un terrain
                d'influence opaque.
            </p>
            <span className='my-4 block text-xl'>L'entreprise</span>

            <p className='text-sm mb-8'>
                Le laboratoire Galaxy Swiss Bourdin (GSB) est issu de la fusion entre le géant américain Galaxy (spécialisé dans le secteur des maladies virales dont le SIDA et les hépatites) et le conglomérat européen
                Swiss Bourdin (travaillant sur des médicaments plus conventionnels), lui-même déjà union de trois
                petits laboratoires.
                En 2022, les deux géants pharmaceutiques ont uni leurs forces pour créer un leader de ce secteur
                industriel. L'entité Galaxy Swiss Bourdin Europe a établi son siège administratif à Paris. Le siège social
                de la multinationale est situé à Philadelphie, Pennsylvanie, aux États-Unis.
                La France a été choisie comme témoin pour l'amélioration du suivi de l'activité de visite
            </p>
            <span className='my-4 block text-xl'>Réorganisation</span>
            <p className='text-sm mb-8'>Une conséquence de cette fusion, est la recherche d'une optimisation de l’activité du groupe ainsi
                constitué en réalisant des économies d’échelle dans la production et la distribution des médicaments
                (en passant par une nécessaire restructuration et vague de licenciement), tout en prenant le meilleur
                des deux laboratoires sur les produits concurrents.
                L'entreprise compte 480 visiteurs médicaux en France métropolitaine (Corse comprise), et 60 dans les
                départements et territoires d'outre-mer. Les territoires sont répartis en 7 secteurs géographiques (Paris-Centre, Sud, Nord, Ouest, Est, DTOM Caraïbes-Amériques, DTOM Asie-Afrique).
                Une vision partielle de cette organisation est présentée ci-dessous.
            </p>
            <Image src={gsb} width={800} height={100} />

            </div>

        </>
    )
}
