import Head from 'next/head'
import Link from 'next/link'
import React, { useEffect } from 'react';
import Typewriter from 'typewriter-effect/dist/core';
import imgCV from "../public/assets/images/imgCv.jpg";


import heroMdl from "../public/assets/images/heroMdl.jpg";
import schema from "../public/assets/images/shemaDB.jpg";



import Image from 'next/image';
export default function Home() {

    return (
        <>
            <Head>
                <title>Accueil</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/engine.ico" />
                <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
            </Head>
            
            <div className='bg-white py-4'>
        <div className='flex justify-between max-w-7xl mx-auto'>
        <Link href="/" className='text-2xl'>FB</Link>
          <ul className='flex items-center space-x-6'>
            <li><Link href="/">Accueil</Link></li>
            <li><Link href="/about">A propos</Link></li>
            <li><Link href="/realisations">Mes réalisation</Link></li>
          </ul>
        </div>
      </div>
            <h1 className='text-center'>Maison des ligues</h1>
            <div className='flex items-center justify-center'>
                <Image src={heroMdl} width={200} height={100} />

            </div>
            <div className='max-w-7xl mx-auto text-white'>
                <span className='my-4 block text-xl'>Le secteur d'activité</span>
                La Maison des Ligues de Lorraine (M2L) a pour mission de fournir des espaces et des services aux différentes ligues sportives régionales et à d’autres structures hébergées. La M2L est une structure financée par le Conseil Régional de Lorraine dont l'administration est déléguée au Comité Régional Olympique et Sportif de Lorraine (CROSL).

                Le site se compose de quatre bâtiments, dont deux dotés de quatre étages et donc de 5 niveaux (les bâtiments A et C) et deux de plain-pied (les bâtiments B et D) dotés d’un seul rez-de-chaussée. Les bâtiments C et D sont neufs. Les bâtiments A et B datent d'une quinzaine d'années.
<br/><br/>
                Les étages des bâtiments A et C hébergent les bureaux des ligues locataires et le rez-de-chaussée des quatre bâtiments héberge des espaces mutualisés : un amphithéâtre de 200 places avec une régie, 8 salles de réunion de 12 à 50 places, un hall d'accueil, une salle de convivialité et son office traiteur, ainsi qu'une salle de formation multimédia dotée de 24 postes. On y trouve également la partie « accueil » des bureaux neuf de l'administration de la M2L. L’autre partie se trouve au premier étage du bâtiment C. Différents locaux de service (archives, stockage local d'entretien ...) se trouvent en sous-sol.

                En fonction de leur taille, les 24 structures hébergées occupent un ou plusieurs bureaux. Au total, la M2L offre 80 bureaux. A chaque étage des bâtiments de bureaux se trouve une petite salle de réunion que les ligues utilisent sans réservation. L'ensemble des autres salles ressources sont accessibles sur réservation, en journée comme en soirée.
                <Image src={schema} width={400} height={600} />

            </div>

        </>
    )
}
